version: "3.8"
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
  gieservice:
    container_name: gestion_des_etudiant
    image: phoenixdd/gieservice:latest
    ports:
      - "5000:5000"
    depends_on:
      - rabbitmq
